#!/usr/bin/env node
// Visual — generates a real, on-brand hero image for one blog post: Claude plans (picks a real
// product + a scene grounded in the article/query), GPT-image-2 renders, Claude verifies the
// real product wasn't misrepresented before anything ships. See agents/ARCHITECTURE.md and
// agents/visual/prompt.md.
//
// Deliberately narrow and manual for now — not wired into Signal's automatic dispatch. Run it
// per-slug, review the PR (GitHub renders the image directly in the diff), merge if it's good.
//
// Usage:
//   node agents/visual/run.mjs <slug> [--query "<target search query>"]   # full pipeline, opens a PR
//   node agents/visual/run.mjs <slug> [--query "..."] --dry-run            # plan only — no image spend, no git
import { readFileSync, existsSync, mkdirSync, writeFileSync, readdirSync, unlinkSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { readEnv } from "../lib/env.mjs";
import { resolveArticle } from "../lib/blog-source.mjs";
import { planVisual, verifyVisual } from "./lib/anthropic.mjs";
import { editImage } from "../content/lib/openai-image.mjs";
import { startTaskBranch, finishTaskPR, abandonTaskBranch, assertCleanFor } from "../lib/git-task-pr.mjs";

const __dir = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dir, "..", "..");
const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
let targetQuery = null;
let slug = null;
for (let i = 0; i < args.length; i++) {
  if (args[i] === "--query") { targetQuery = args[++i] ?? null; continue; }
  if (args[i] === "--dry-run") continue;
  if (!slug) slug = args[i];
}

const OUTPUT_PATH = `public/blog/${slug}.jpg`;
const BRAND_STYLE =
  "Premium editorial product photography for a luxury automotive/home fragrance brand called " +
  "Autivara. Keep the product in the reference image EXACTLY as it appears — same shape, color, " +
  "material, and branding — do not redesign or reimagine the product itself. Only change the " +
  "surrounding scene/context. Photorealistic, soft natural light, no visible added text or logos.";

function git(cmdArgs) {
  return execFileSync("git", cmdArgs, { cwd: ROOT, encoding: "utf8" }).trim();
}

function mimeFor(filename) {
  const ext = filename.split(".").pop()?.toLowerCase();
  return ext === "png" ? "image/png" : ext === "webp" ? "image/webp" : "image/jpeg";
}

// Only products with at least one real, staged local photo are usable references — a product
// with no photos (product-pipeline/catalog-novelty.json can list one with images: []) can't
// ground a real recontextualization.
function buildCatalogSummary() {
  const catalog = JSON.parse(readFileSync(join(ROOT, "product-pipeline", "catalog-novelty.json"), "utf8"));
  return catalog.products
    .map((p) => {
      const dir = join(ROOT, "public", "products", p.handle);
      let imageCount = 0;
      if (existsSync(dir)) {
        while (existsSync(join(dir, `${p.handle}-${imageCount + 1}.jpg`))) imageCount++;
      }
      return { handle: p.handle, title: p.title, type: p.type, tags: p.tags, price: p.price, image_count: imageCount };
    })
    .filter((p) => p.image_count > 0);
}

function renderPrompt(scene, retryNote) {
  return `${BRAND_STYLE} New scene: ${scene}${retryNote ? ` CRITICAL: ${retryNote}` : ""}`;
}

// Real-incident-driven safety net: on 2026-07-27 a media-type bug in the verification step
// crashed AFTER a real, paid GPT-image-2 generation had already succeeded — the generated bytes
// only ever lived in memory, so the crash meant paying again on retry. Every render is now cached
// to disk immediately, keyed by a hash of its exact prompt (first attempt and retry-with-
// corrected-prompt are different prompts, so they get different cache entries) — any crash
// downstream of generation (a code bug, a network blip, anything) can be retried without
// re-spending, as long as the plan/prompt hasn't changed. Cleared once a run actually ships
// (opens a PR) or exhausts its retries, since a shipped or already-rejected image has no reason
// to linger.
const CACHE_DIR = join(ROOT, "agents", "visual", ".cache");

async function editImageCached(apiKey, refBuffer, refFilename, prompt) {
  const hash = createHash("sha256").update(prompt).digest("hex").slice(0, 16);
  const cachePath = join(CACHE_DIR, `${slug}-${hash}.jpg`);
  if (existsSync(cachePath)) {
    console.log(`Visual: reusing already-generated image for this exact prompt (no new charge) → ${cachePath}`);
    return readFileSync(cachePath);
  }
  const buffer = await editImage(apiKey, refBuffer, refFilename, prompt);
  mkdirSync(CACHE_DIR, { recursive: true });
  writeFileSync(cachePath, buffer);
  return buffer;
}

function clearCacheFor(targetSlug) {
  if (!existsSync(CACHE_DIR)) return;
  for (const f of readdirSync(CACHE_DIR)) {
    if (f.startsWith(`${targetSlug}-`)) { try { unlinkSync(join(CACHE_DIR, f)); } catch {} }
  }
}

(async () => {
  if (!slug) throw new Error('Usage: node agents/visual/run.mjs <slug> [--query "..."] [--dry-run]');
  const { ANTHROPIC_API_KEY, OPENAI_API_KEY } = readEnv(["ANTHROPIC_API_KEY", "OPENAI_API_KEY"]);
  const systemPrompt = readFileSync(join(__dir, "prompt.md"), "utf8");

  // Refuse to overwrite — matches agents/content/generate-blog-image.mjs's existing guard. This
  // is real per-image money; regenerating an existing hero image should be a deliberate choice
  // (delete the file yourself first), never an accidental re-run.
  if (existsSync(join(ROOT, OUTPUT_PATH))) {
    throw new Error(`${OUTPUT_PATH} already exists — delete it first if you want to regenerate.`);
  }
  if (!dryRun) assertCleanFor([OUTPUT_PATH], ROOT);

  const resolved = resolveArticle(slug);
  if (!resolved) throw new Error(`Could not find article for slug "${slug}"`);
  const article = {
    slug,
    title: resolved.article.title,
    category: resolved.article.category,
    excerpt: resolved.article.excerpt,
    content: resolved.article.content.slice(0, 6),
  };
  const catalog = buildCatalogSummary();

  console.log(`Visual: planning hero image for ${slug}${targetQuery ? ` (query: "${targetQuery}")` : ""}...`);
  const { output: plan, usage: planUsage } = await planVisual({ apiKey: ANTHROPIC_API_KEY, systemPrompt, article, targetQuery, catalog });
  console.log(`\nplan: ${plan.product_handle} (photo #${plan.reference_image_index})`);
  console.log(`scene: ${plan.scene}`);
  console.log(`rationale: ${plan.rationale}`);
  console.log(`usage: ${planUsage.input_tokens} in / ${planUsage.output_tokens} out`);

  const product = catalog.find((p) => p.handle === plan.product_handle);
  if (!product) throw new Error(`Plan referenced unknown product handle "${plan.product_handle}" — not in catalog or has no local photos`);
  if (plan.reference_image_index < 1 || plan.reference_image_index > product.image_count) {
    throw new Error(`Plan's reference_image_index (${plan.reference_image_index}) is out of range for ${plan.product_handle} (has ${product.image_count} photo(s))`);
  }

  if (dryRun) {
    console.log("\n--dry-run: plan only. No image generated, no spend, no git.");
    return;
  }

  const refFilename = `${plan.product_handle}-${plan.reference_image_index}.jpg`;
  const refPath = join(ROOT, "public", "products", plan.product_handle, refFilename);
  const refBuffer = readFileSync(refPath);
  const refMediaType = mimeFor(refFilename);

  console.log(`\nVisual: generating image (GPT-image-2 edit, real cost per call)...`);
  let imageBuffer = await editImageCached(OPENAI_API_KEY, refBuffer, refFilename, renderPrompt(plan.scene));

  console.log("Visual: verifying the product wasn't misrepresented...");
  let verification = await verifyVisual({
    apiKey: ANTHROPIC_API_KEY,
    referenceImageBase64: refBuffer.toString("base64"),
    referenceMediaType: refMediaType,
    generatedImageBase64: imageBuffer.toString("base64"),
  });
  console.log(`verified: ${verification.output.product_preserved} — ${verification.output.notes}`);

  if (!verification.output.product_preserved) {
    console.warn(`Visual: first attempt failed verification (${verification.output.discrepancies.join("; ")}) — retrying once with a corrected prompt.`);
    const retryNote = `the previous attempt altered the product in these ways: ${verification.output.discrepancies.join("; ")}. Do not repeat these changes — reproduce the product's shape, color, material, and branding EXACTLY as shown in the reference photo, changing only the surrounding scene.`;
    imageBuffer = await editImageCached(OPENAI_API_KEY, refBuffer, refFilename, renderPrompt(plan.scene, retryNote));
    verification = await verifyVisual({
      apiKey: ANTHROPIC_API_KEY,
      referenceImageBase64: refBuffer.toString("base64"),
      referenceMediaType: refMediaType,
      generatedImageBase64: imageBuffer.toString("base64"),
    });
    console.log(`retry verified: ${verification.output.product_preserved} — ${verification.output.notes}`);
  }

  if (!verification.output.product_preserved) {
    throw new Error(
      `Visual: image failed verification twice (${verification.output.discrepancies.join("; ")}) — not shipping. ` +
      `Try a different reference photo or product, or write the scene more explicitly.`
    );
  }

  // A lightweight task-shaped object — reuses git-task-pr.mjs as-is (branch/PR-body logic) without
  // requiring this to be a real Signal task. Not wired into Signal's task store; this agent isn't
  // dispatched by Signal yet, per the "narrow, manual, prove-it-first" build decision.
  const pseudoTask = {
    id: slug,
    agent: "visual",
    action: `Generate a hero image for ${article.title}`,
    target_url: `/blog/${slug}`,
    hypothesis: plan.rationale,
    expected_effect: "A distinctive, on-brand hero image replaces the generic category fallback photo for this page.",
    check_back_on: "n/a — visual asset, not a ranking intervention",
    evidence: { product_handle: plan.product_handle, reference_image_index: plan.reference_image_index, scene: plan.scene, target_query: targetQuery ?? null },
  };

  let startBranch = null;
  try {
    ({ startBranch } = startTaskBranch(pseudoTask, ROOT));
    mkdirSync(join(ROOT, "public", "blog"), { recursive: true });
    writeFileSync(join(ROOT, OUTPUT_PATH), imageBuffer);
    console.log(`Visual: wrote ${OUTPUT_PATH}.`);

    const prUrl = finishTaskPR({
      task: pseudoTask,
      files: [OUTPUT_PATH],
      commitMessage: `visual: hero image for ${slug}`,
      cwd: ROOT,
      startBranch,
    });
    console.log(`Visual: opened PR → ${prUrl}`);
    clearCacheFor(slug);
  } catch (e) {
    try { git(["checkout", "--", OUTPUT_PATH]); } catch {}
    try { git(["checkout", startBranch]); } catch {}
    abandonTaskBranch(pseudoTask, ROOT);
    console.error(`Visual: FAILED after generating a verified image — nothing was committed.`);
    throw e;
  }
})().catch((e) => { console.error("FATAL:", e.message); process.exit(1); });
